#lang sicp

;; sine of an angle can be computed by making use of approximation
;; sinx = x if x is sufficiently small

;; sinx = 3sin(x/3) - 4sin^3(x/3)
(define limit 0.1)

(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle count)
  (if (not (> (abs angle) 0.1))
      count
      (p (sine (/ angle 3.0)
               (+ count 1)))))

;; a. How many times is the procedure p applied when
;; sine 12.15 is evaluated?
(sine 12.15 1)
;; b. what is the order of growth in space and number of steps
;; as a function of a usedby the process generated by the sine procedure
;; when (sine a) is evaluated



